### ISSUE TITLE
Artefact naming

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#27]
https://github.com/adnanrahic/boilerplate-api/blob/da758e64496d98c3eee003eb8219b24b317f2877/.semaphore/semaphore.yml#L18

It is not good practice to use only git branch name when naming artefacts (in this case image tag) generated by CI/CD system.

With any sort of rebuild things can easily get out of sync and such issues are _very_ hard to find.
(I can elaborate on the scenarios if you want me to)

Every artefact name should contain some semaphore identifier (workflow id or pipeline id) depending on intended use case. `SEMAPHORE_WORKFLOW_ID` should be ok here.

Something like:
```
TAG=${SEMAPHORE_GIT_BRANCH}_${SEMAPHORE_WORKFLOW_ID}
``` 
or, since you already checked out code
```
GIT_HASH=$(shell git log --format=format:'%h' -1)
TAG=${SEMAPHORE_GIT_BRANCH}_${GIT_HASH}_${SEMAPHORE_WORKFLOW_ID}
```
Having part of the commit sha in the tag name makes it easier to connect image to actual commit, if need arises (and it does).

**Comment by adnanrahic** [comment]
Hey! 
Thanks for the detailed explanation. I've added the `$TAG` to include the branch, git hash, and workflow id. The refactored version is now using the pattern:
```
GIT_HASH=$(git log --format=format:'%h' -1)
TAG=${SEMAPHORE_GIT_BRANCH}_${GIT_HASH}_${SEMAPHORE_WORKFLOW_ID}
```

**Comment by adnanrahic** [comment]
Here's where it was added:

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L69-L70

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L86-L87

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/push-image.yml#L15-L16

**Comment by predrag-rakic** [comment]
:+1:
