### ISSUE TITLE
Sem 2 caching

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#28]
Since this is production grade example caching should be used whenever there is building involved (that includes testing).

Darko provided examples in this uncut episode https://www.youtube.com/watch?v=t6Sp1nBtcJo

**Comment by adnanrahic** [comment]
There's not much I can do without artifact caching. I've added dependency caching where possible. But, without a way to cache Docker images, there's no real way to do it properly. :disappointed:

**Comment by adnanrahic** [comment]
Just leaving where I added the caching:

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L9-L17

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L72

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L92

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L106

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L112

https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L118

**Comment by predrag-rakic** [comment]
First block called "Install dependencies" is there only to cache dependencies.

It is better to do node dependency caching where node dependencies are used, in job called "npm run lint". 
The job can look something like:
```
- checkout
- cache restore node_modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json),node_modules-$SEMAPHORE_GIT_BRANCH-,node_modules
- npm i
- npm run lint
- cache store node_modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json) node_modules
```

**Comment by adnanrahic** [comment]
Removed the install and cache dependencies block and added the caching to `npm run lint`.

**Comment by predrag-rakic** [comment]
:+1:
