### ISSUE TITLE
Deploying in separate pipeline

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#29]
https://github.com/adnanrahic/boilerplate-api/blob/da758e64496d98c3eee003eb8219b24b317f2877/.semaphore/semaphore.yml#L83

If deployment is in the same pipeline with building and testing there is no easy way to do rollback latter:
Scenario: 
Workflow A deployed containers it generated and production works fine.
After some time new commit comes in and new workflow B deploys containers it generated but after some time it turns out that something is wrong with new code and that it needs to be rolled-back.
The way to do it with this setup is to make new commit.
But if this pipeline is split in 2 pipelines and the second one is activated by manual promotion then rollback is just promoting to production from workflow A again (no git commit involved). 

See more about promotions at https://www.youtube.com/watch?v=6uAQfxHhV-o&t=11s

**Comment by adnanrahic** [comment]
The deploy step is now a promotion after the build and push step. I've added an automatic promotion for staging and an automatic for production only if the branch is `master`. Otherwise, it has to be triggered manually.

**Comment by adnanrahic** [comment]
The deployment steps will be triggered by promotions automatically. 
https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/push-image.yml#L30-L40

**Comment by predrag-rakic** [comment]
:+1:
