### ISSUE TITLE
Skip tests

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#30]
https://github.com/adnanrahic/boilerplate-api/blob/da758e64496d98c3eee003eb8219b24b317f2877/.semaphore/semaphore.yml#L64

Having functionality that i'm going to describe here is arguable desirable.

In setup as is (even with 2 pipelines) user has to wait for all tests to be finished before images are created before they can be deployed.

If this block (image creation block) is placed in separate pipeline (second one and deploy moved to third pipeline in sequence) then testing can be bypassed in case of DevOps emergency.

In order to achieve this production image cannot be tagged with SEMAPHORE_WORKFLOW_ID any more because there can potentially be more of them generated by different promotions.
https://github.com/adnanrahic/boilerplate-api/blob/da758e64496d98c3eee003eb8219b24b317f2877/.semaphore/semaphore.yml#L73
So, semaphore id that need to be used here is SEMAPHORE_PIPELINE_1_ARTEFACT_ID (one because image is generated by second pipeline in workflow - counting from zero)

Maybe you wander why not put together last 2 blocks (build image and deploy) in single pipeline?
Last two blocks should not be lumped together in the same pipeline because in that case there is no way to do clean roolback of the previously working image. And DevOps people really want that.

**Comment by adnanrahic** [comment]
I've separated the build and push of the production images from the main pipeline. Now the tests can be skipped if you want to. The tag now looks like this:
```
docker build --cache-from $API_IMAGE:$TAG --tag $API_IMAGE:$SEMAPHORE_PIPELINE_1_ARTEFACT_ID .
```

**Comment by adnanrahic** [comment]
The pipeline for building and deploying production images is now separated from the main pipeline.
https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/push-image.yml#L2

It's triggered from an automatic promotion from the main pipeline.
https://github.com/adnanrahic/boilerplate-api/blob/d6f76af9abf91adbcaad7c61ce3d153628843498/.semaphore/semaphore.yml#L123-L127

**Comment by predrag-rakic** [comment]
:+1:
