### ISSUE TITLE
Mongo

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#31]
https://github.com/adnanrahic/boilerplate-api/blob/e0a656bdfde0ff56cbd4fa8ce9c34959cc239b80/.semaphore/semaphore.yml#L19

Mongo service is being worked on as we speak.
Should be ready soon.
If not, docker compose will do...

Just wondering, why is docker-compose necessary? 
Isn't it enough to replace lines 45 and 52 with `docker run mongo...`?

**Comment by adnanrahic** [comment]
That's a nice solution for the time being. I'll add that.

**Comment by predrag-rakic** [comment]
ok
I see this is not done yet.

According to this document https://docs.google.com/document/d/1yygwDhs6nbn0HfTQeRlL3Ho9ElfUcDYwjUCkXFmI5w8/edit?ts=5bcd87ae
 docker-compose should be used.

Closing this issue.
