### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#32]
https://github.com/adnanrahic/boilerplate-api/blob/e0a656bdfde0ff56cbd4fa8ce9c34959cc239b80/.semaphore/push-images.yml#L35

There is no need for this tag.
The one from the first job containing branch name and begging of git SHA is much more useful.
This whole job can be removed.

Even if there is need for 2 (or more) tags for the same docker image, it is ok to push it from the same job because first push uploads layers, the rest finish quickly with "Layer already exists"

**Comment by adnanrahic** [comment]
I've removed the whole job.

**Comment by predrag-rakic** [comment]
:+1:
