### ISSUE TITLE
Delete cache entry

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#33]
https://github.com/adnanrahic/boilerplate-api/blob/e0a656bdfde0ff56cbd4fa8ce9c34959cc239b80/.semaphore/push-images.yml#L46

If there is only one job in this pipeline, there is no need for this promotion.
`cache delete` can be the last command in the first (and only) job.

**Comment by adnanrahic** [comment]
I've removed the promotion and added the cache delete as the last command in the Push Images job.

**Comment by predrag-rakic** [comment]
:+1:
