### ISSUE TITLE
update/generate deployment manifest

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#35]
https://github.com/adnanrahic/boilerplate-api/blob/fd9f58abc168a301d2896274141809a4cb286a18/.semaphore/deploy-staging.yml#L18

Each deployment invocation will need to deploy container with different tag

FYI: we use envsubst (https://www.systutorials.com/docs/linux/man/1-envsubst/)

**Comment by adnanrahic** [comment]
https://github.com/adnanrahic/boilerplate-api/blob/83902101d44e3821936616111c95ba598d3ecfe4/.semaphore/deploy-prod.yml#L9

I used `envsubst` for adding the tags in the deployment files.
