### ISSUE TITLE
Write unit tests for UserController.js

### ISSUE THREAD

**Issue by adnanrahic** [adnanrahic/boilerplate-api#8]
This is a small issue regarding the unit test support for the UserController.js. The NoteController.js has unit test coverage implemented. In the [`test/unit/Note.spec.js`](https://github.com/adnanrahic/boilerplate-api/blob/master/test/unit/Note.spec.js) you can see the layout of the tests. Implement this same style of testing for the UserController.js. Create a new file named `User.spec.js` in the [`test/unit/`](https://github.com/adnanrahic/boilerplate-api/tree/master/test/unit) directory, and add simple unit tests. In order to create valid tests please add the appropriate lines of code to `UserController.js`. View `NoteController.js` for reference.

**Comment by m8r1x** [comment]
Hi @adnanrahic I could probably take this. 😃

**Comment by m8r1x** [comment]
Should the routes also be tested or should it resemble exactly what's in [`test/unit/Note.spec.js`](https://github.com/adnanrahic/boilerplate-api/blob/master/test/unit/Note.spec.js)?

**Comment by adnanrahic** [comment]
Hey @m8r1x ! Sure, be my guest go ahead and take this issue. Well, you don't need to add tests for the routes if you don't want to. It's fine to start with adding the basic unit tests similar as with [`test/unit/Note.spec.js`](https://github.com/adnanrahic/boilerplate-api/blob/master/test/unit/Note.spec.js). I usually test the routes with e2e tests. But if you have any cool ideas about unit testing the routes as well, go for it!

**Comment by m8r1x** [comment]
Awesome!!! I'll probably add the User e2e test since it's not there. 😄

**Comment by adnanrahic** [comment]
Hey @m8r1x . Just a heads up. I've just merged a PR for refactoring the `UserController.js`. The functionality should stay the same in regards to the tests you'll be writing. This is just to let you know after pulling master again not to get surprised by the new code. :smile:
