### ISSUE TITLE
Refactor UserController.js to use 'provider style' syntax

### ISSUE THREAD

**Issue by adnanrahic** [adnanrahic/boilerplate-api#9]
The current style of writing in the `UserController.js` is a simple router with callback functions on every route. Refactor this style to use provider methods as done with the `NoteController.js`. This means adding a new file called `UserProvider.js` and abstracting away the callback functions from the `UserController.js` to the `UserProvider.js`. If any additional questions need answering, feel free to add them to this thread! :smile:

**Comment by ErdtR** [comment]
Hi @adnanrahic. Can I help you with it?

**Comment by adnanrahic** [comment]
Hey @ErdtR. Of course, go for it. You can reference the `NoteController.js` and `NoteProvider.js` to see how I did it, if you get stuck.

**Comment by ErdtR** [comment]
@adnanrahic I see that `createNote`, `deleteNote` and `updateNote` routes have  a `VerifyToken` middleware. Should I add this middleware to `createUser`, `deleteUser` and `updateUser` routes?

**Comment by adnanrahic** [comment]
@ErdtR Sure. You can add the middleware to those routes.
